# This workflow will build geo-11 for Release use.
# This workflow builds a test artifact without modifying the repository.
#
# To make a new Release, Tag a successful build, and the release_on_tag.yml will run.

name: HelixMod Manual Build

# Run manually, or automatically when files that affect the build are changed.
on:
  push:
    branches:
      - master
    paths:
      - 'HLSLDecompiler/**'
      - 'BinaryDecompiler/**'
      - 'D3D_Shaders/**'
      - '**/*.vcxproj'
      - '**/*.sln'
      - 'Publish.bat'
      - 'Version.h'
      - '.github/workflows/zip_release.yml'
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Create ZipRelease for HelixMod use'
        # Default value if no value is explicitly provided
        default: 'World'
        # Input has to be provided for the workflow to run
        required: true

# This is a copy of the msbuild.yml action script. The setup to
# call out to another job is too restrictive, so let's just duplicate
# the sequence, but upload different artifact here.

jobs:
  zip_release_workflow:

    # Now runs on latest runners with VS2022 as default.
    runs-on: windows-2022

    steps:
    - name: Checkout branch master
      uses: actions/checkout@v4

    - name: Show all Visual Studio installs
      shell: cmd
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all
        echo(
        echo === Installed VS ===
        dir "C:\Program Files (x86)\Microsoft Visual Studio"
        dir "C:\Program Files\Microsoft Visual Studio"
        echo(
        echo === Installed toolsets ===
        dir "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC"
        dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC"
          
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
      
# VisualStudio2022 should be there in 'windows-latest'       
#      with:
#        vs-version: '2022'

    - name: Build via Publish.bat
      shell: cmd
      run: call .\Publish.bat RELEASE
        
# Now we can upload the remaining artifacts as the HelixMod version.
# These artifacts are for testing, and not actual Releases.

    - name: Upload HelixMod build
      uses: actions/upload-artifact@v4
      with:
        name: 3Dmigoto-build-${{github.run_number}}
        path: Zip Release\
